language: python
dist: xenial
python:
  - '3.6'
  - '3.7'
  - '3.8'
install: pip install --ignore-installed -r requirements.txt && pip install --ignore-installed -r requirements-dev.txt
script:
 - nosetests
